import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/layout/Header";
import SideBar from "@/navigation/Sidebar";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Import Material Symbols */}
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
      </head>
      <body className={roboto.className}>
        <Header />
        <main className="flex overflow-hidden h-[calc(100vh-64px)]">
          <SideBar />
          {children}
        </main>
        
      </body>
    </html>
  );
}
